<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Comments extends Model
{
	use HasFactory;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array<int, string>
	 */
	protected $fillable = [
		'user_id',
		'post_id',
		'text',
		'status', // 'publish','pending','trash'

	];

	protected static function boot()
	{
		parent::boot(); // TODO: Change the autogenerated stub

		static::creating(function ($comment) {
			// Set Article Status
			if (empty($comment->status)) {
				$comment->status = 'pending';
			}
		});
	}
}