<?php

namespace App\Models;

use App\Traits\Scope;
use App\Traits\Sluggable;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use fxcjahid\LaravelEditorJsHtml\BlocksManager;
use Illuminate\Database\Eloquent\Factories\HasFactory;


class Post extends Model
{
    use HasFactory, Sluggable, Scope, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'title',
        'name',
        'content',
        'user_id',
        'status', // 'publish','draft','scheduled','trash' 
    ];

    protected $cats = [
        'thumbnail' => 'array',
    ];

    /**
     * The attribute that will be slugged.
     *
     * @var string
     */
    protected $slugAttribute = 'title';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($post) {

            $post->content = self::setContent($post->content);

            // Set Article Status
            if (empty($post->status)) {
                $post->status = 'draft';
            }
        });
    }

    private static function setContent($content)
    {
        if (empty($content)) {
            return json_encode([
                'time'    => round(microtime(true) * 1000),
                'blocks'  => [],
                'version' => '2.27.0',
            ], JSON_PRETTY_PRINT);
        } else {
            if (! isValidEditorJsBlocks($content)) {
                return ConvertPlaneTextToEditorJsBlocks($content);
            }
        }

        return $content;
    }

    /**
     * Generate post url
     * @return string
     */
    public function url()
    {
        $category = ! empty($this->category[0]->slug) ? $this->category[0]->slug : 'draft';

        return route('post.show', [$category, $this->slug]);
    }

    /**
     * Get post thumbnail image
     * @param string $size 
     */
    public function image($size = null)
    {
        $image = ! empty(isset($this->thumbnail[0]->medium))
            ? $this->thumbnail[0]->medium
            : null;

        return $image;
    }


    /**
     * Get Post content only Text Format
     * @return string 
     */
    private function getContentText()
    {
        $blocksManager = new BlocksManager($this->content);
        $text          = $blocksManager->renderText();

        return $text;
    }

    /**
     * Get Post content Html Format
     * @return string
     */
    private function getContentHtml()
    {
        $blocksManager = new BlocksManager($this->content);
        $html          = $blocksManager->renderHtml();

        return $html;
    }

    /**
     * Modifed Summary if is empty
     * Fillup Summary from body
     */
    public function getSummaryAttribute()
    {
        $contentText = $this->getContentText();
        $summary     = Str::words($contentText, 400, '');

        return ! empty($this->summary) ? $this->summary : $summary;
    }

    /**
     * Modified Post Content 
     * Remove Tags, Json,
     * @return string
     */
    public function getBodyAttribute()
    {
        return json_encode([
            'text' => $this->getContentText(),
            /**
             * Don't use HTML Render it's take long Loading Time
             */
            //'html'	=> $this->getContentHtml(),
        ]);
    }


    /**
     * Get publish aricles link for Sitemap
     */
    public static function sitemap()
    {
        return self::where('status', '=', 'publish')
            ->with([
                'category' => function ($query) {
                    $query->select([
                        'id',
                        'slug',
                    ]);
                }
            ])
            ->get([
                'id',
                'slug',
                'updated_at',
            ])
            ->makeHidden([
                'user_id',
                'summary',
                'status',
                'readTime',
                'pivot',
                'content',
                'created_at',
                'deleted_at',
                'body',
            ])
            ->map(function ($each) {
                return [
                    'url'     => route('post.show', [
                        'slug'     => $each->slug,
                        'category' => $each->category[0]['slug'],
                    ]),
                    'lastmod' => $each->updated_at,
                ];
            });
    }


    /**
     * Get Publist post by count row
     * @return count
     */
    public static function getPublish()
    {
        return Post::withCount('s')
            ->where('status', '=', 'publish')
            ->get();
    }

    /**
     * Checking exiting Slug or ID
     */
    public static function existSlugOrID($ID)
    {
        return self::where('id', $ID)
            ->orWhere('slug', $ID)->exists();
    }

    /**
     * Create New Post
     */
    public static function CreatePost()
    {
        return self::Create(
            [
                'user_id' => auth()->id(),
            ],
        )->fresh();
    }

    /**
     * Find exiting post By Slug Or ID
     */
    public static function findBySlugOrID($find)
    {
        return self::with([
            'user',
            'tag',
            'category',
            'series',
            'thumbnail',
            'comments',
        ])->where('slug', $find)
            ->orWhere('id', $find)
            ->firstOrFail();
    }

    /**
     * Get all post 
     * @return mixed
     */
    public static function getAll()
    {
        return self::with([
            'user',
            'tag',
            'category',
            'thumbnail',
        ]);
    }

    /** 
     * Get active post by slug
     * @return mixed
     **/
    public static function findPublishPost($category, $post)
    {
        return self::WithThumbnail()
            ->WithTag()
            ->WithComments()
            ->WherePublished()
            ->WhereCategory($category)
            ->whereSlug($post)
            ->firstOrFail();
    }

    /**
     * Count post statistics
     * @var all
     * @var publish
     * @var draft
     * @var scheduled
     * @var trash
     * @return mixed
     */
    public static function statistics()
    {
        $all        = self::count('status');
        $publish    = self::where('status', '=', 'publish')->count('status');
        $draft      = self::where('status', '=', 'draft')->count('status');
        $trash      = self::where('status', '=', 'trash')->count('status');
        $scheduled  = self::where('status', '=', 'scheduled')->count('status');
        $lastUpdate = self::where('updated_at', '>', now()->subDays(10)->endOfDay())->count('id');

        return (object) array(
            'all'        => $all,
            'publish'    => $publish,
            'draft'      => $draft,
            'trash'      => $trash,
            'scheduled'  => $scheduled,
            'lastUpdate' => $lastUpdate,
        );
    }

    /**
     * Get post Creator
     * Relation between table
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get post Comments
     * Relation between table
     */
    public function comments()
    {
        return $this->hasMany(PostComments::class);
    }

    /**
     * Get post Categories
     * Relation between table
     */
    public function category()
    {
        return $this->belongsToMany(Categories::class, 'post_categories');
    }

    /**
     * Get post series
     * Relation between table
     */
    public function series()
    {
        return $this->belongsToMany(Series::class, 'post_series');
    }

    /**
     * Get suggestion post by category,tag
     * Relation between table
     * @return mixed
     */
    public static function suggestion(Post $post)
    {
        return self::WhereHas('tag', function ($query) use ($post) {
            return $query
                ->whereIn('name', $post->tag->pluck('name'));
        })
            ->orWhereHas('category', function ($query) use ($post) {
                return $query
                    ->whereIn('name', $post->category->pluck('name'));
            })
            ->where('id', '!=', $post->id) // So you won't fetch same post
            ->where('status', '=', 'publish')
            ->inRandomOrder()
            ->take(10) // Limitation 
            ->get([
                'id',
                'name',
                'slug',
            ])
            ->makeHidden(['body']);
    }

    /**
     * Get related post by category wise
     * Relation between table
     * @return mixed
     */
    public static function related(Post $post)
    {
        return self::whereHas('category', function ($query) use ($post) {
            return $query->whereIn('name', $post->category->pluck('name'));
        })
            ->where('id', '!=', $post->id) // So you won't fetch same post
            ->where('status', '=', 'publish')
            ->take(3)
            ->with([
                'thumbnail',
            ])
            ->get();
    }

    /**
     * Get post Tags
     * Relation between table
     */
    public function tag()
    {
        return $this->belongsToMany(Tag::class, 'post_tags');
    }

    /**
     * Get post Thumbnail
     * Relation between table
     */
    public function thumbnail()
    {
        return $this->belongsToMany(File::class, 'post_thumbnails');
    }


}