<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Tag extends Model
{
	use HasFactory;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array<int, string>
	 */
	protected $fillable = [
		'name',
		'user_id',
		'slug',
		'description',
		'is_active'
	];

	protected $casts = [
		'is_active' => 'boolean',
	];


	protected static function boot()
	{
		parent::boot(); // TODO: Change the autogenerated stub

		static::creating(function ($tag) {
			// Set auth user id
			$tag->user_id = auth()->id();

			// Create Tag URL
			if (empty($tag->slug)) {
				$tag->slug = Str::slug($tag->name);
			}

			// Set Tag Status
			if (empty($tag->is_active)) {
				$tag->is_active = true;
			}
		});
	}


	/**
	 * Get post attached 
	 * Relation between table
	 */
	public function post()
	{
		return $this->belongsToMany(Post::class, 'post_tags');
	}
}